### ISSUE TITLE
Build failed in Ld ObjectiveGit

### ISSUE THREAD

**Issue by cbfiddle** [gitx/gitx#196]
Following the build instructions on 10.14.6, I get this error (the same error for release and debug):

```
Scripts/build.py debug
Building scheme GitX (debug), please wait…
** BUILD FAILED **


The following build commands failed:
	Ld /Volumes/A/gitx/build/Debug/ObjectiveGit.framework/Versions/A/ObjectiveGit normal x86_64
(1 failure)
Traceback (most recent call last):
  File "Scripts/build.py", line 40, in <module>
    args.func(args)
  File "Scripts/build.py", line 31, in build_cmd
    build(project)
  File "Scripts/build.py", line 14, in build
    helpers.xcodebuild(project.scheme(), project.workspace(), project.current_build_config(), ["build"], project.build_base_dir())
  File "/Volumes/A/gitx/Scripts/helpers.py", line 53, in xcodebuild
    raise BuildError(str(e))
helpers.BuildError: Command '['xcrun', 'xcodebuild', '-workspace', u'GitX.xcworkspace', '-scheme', u'GitX', '-configuration', 'Debug', 'build', 'BUILD_DIR=/Volumes/A/gitx/build']' returned non-zero exit status 65

```

**Comment by bcomnes** [comment]
It looks like homebrew installs openssl to a new location now: `/usr/local/opt/openssl@1.1`.  I dont know what I exactly did, but swapping the header imports inside of Xcode for both objective-git and Gitx to point to that new location, I was able to build.  I was unable to properly sign the app though.  Still runs locally.  What a mess gitx has become :(  I would gladly pay some money for a prebuilt version on the App Store.   Nonetheless, I appreciate any and all recent efforts into updates and changes.

**Comment by jphalip** [comment]
I was able to fix it by creating the link manually:

```
ln -s /usr/local/opt/openssl@1.1 /usr/local/opt/openssl
```

**Comment by jasonkarns** [comment]
@bcomnes I'd be wary of simply swapping the header imports. If I understand correctly, that is precisely the scenario that homebrew is attempting to avoid: your build is pointing to homebrew's _headers_ but linking against the _non homebrew_ version.

> Warning: Refusing to link: openssl
Linking keg-only OpenSSL means you may end up linking against the insecure,
deprecated system version while using the headers from the Homebrew version.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib

**Comment by claytonrcarter** [comment]
I'm in the same boat. (macOS 10.15.4, Xcode 11.4.1, Homebrew 2.2.15, openssl 1.1.1g) Is anybody able to build this?

 I must have updated openssl via Homebrew and now the last build I made (that was working perfectly, thank you very much :) is crashing on launch as it's looking for `/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib` which doesn't exist anymore. (I think this is #200.)

When I try to re-clone, init and build it from the instructions on the wiki, I end up with
```
** BUILD FAILED **


The following build commands failed:
	Ld /Users/crcarter/Software/Other/GitX/gitx/build/Release/ObjectiveGit.framework/Versions/A/ObjectiveGit normal x86_64
```

When I try the `xcrun` manually, I end up with this:
```sh
$ xcrun xcodebuild -workspace GitX.xcworkspace -scheme GitX -configuration Release build BUILD_DIR=/Users/crcarter/Software/Other/GitX/gitx/build
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace GitX.xcworkspace -scheme GitX -configuration Release build BUILD_DIR=/Users/crcarter/Software/Other/GitX/gitx/build

Build settings from command line:
    BUILD_DIR = /Users/crcarter/Software/Other/GitX/gitx/build

note: Using new build system
note: Building targets in parallel
note: Planning build
note: Using build description from disk

... lots of build commands and such ...

Ld /Users/crcarter/Software/Other/GitX/gitx/build/Release/ObjectiveGit.framework/Versions/A/ObjectiveGit normal x86_64 (in target 'ObjectiveGit-Mac' from project 'ObjectiveGitFramework')
    cd /Users/crcarter/Software/Other/GitX/gitx/External/objective-git
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-macos10.8 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -L/Users/crcarter/Software/Other/GitX/gitx/build/Release -L. -LExternal -L/usr/local/opt/openssl/lib -L/Users/crcarter/Software/Other/GitX/gitx/External/objective-git/External/build/lib -F/Users/crcarter/Software/Other/GitX/gitx/build/Release -filelist /Users/crcarter/Library/Developer/Xcode/DerivedData/GitX-fuwqtzoxlnpfhxcovjaqievpfxyk/Build/Intermediates.noindex/ObjectiveGitFramework.build/Release/ObjectiveGit-Mac.build/Objects-normal/x86_64/ObjectiveGit.LinkFileList -install_name @rpath/ObjectiveGit.framework/ObjectiveGit -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/../Frameworks -Xlinker -object_path_lto -Xlinker /Users/crcarter/Library/Developer/Xcode/DerivedData/GitX-fuwqtzoxlnpfhxcovjaqievpfxyk/Build/Intermediates.noindex/ObjectiveGitFramework.build/Release/ObjectiveGit-Mac.build/Objects-normal/x86_64/ObjectiveGit_lto.o -fobjc-arc -fobjc-link-runtime -fapplication-extension -lgit2 -force_load External/libgit2.a /usr/local/lib/libssh2.a -lcrypto -lssl -lcurl -lz -liconv -lgit2 -framework Cocoa -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/crcarter/Library/Developer/Xcode/DerivedData/GitX-fuwqtzoxlnpfhxcovjaqievpfxyk/Build/Intermediates.noindex/ObjectiveGitFramework.build/Release/ObjectiveGit-Mac.build/Objects-normal/x86_64/ObjectiveGit_dependency_info.dat -o /Users/crcarter/Software/Other/GitX/gitx/build/Release/ObjectiveGit.framework/Versions/A/ObjectiveGit
ld: warning: directory not found for option '-L/usr/local/opt/openssl/lib'
ld: warning: directory not found for option '-L/Users/crcarter/Software/Other/GitX/gitx/External/objective-git/External/build/lib'
ld: library not found for -lcrypto
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

If I do @jphalip tip of manually linking the directories, the error changes to:
```sh
Ld /Users/crcarter/Software/Other/GitX/gitx/build/Release/ObjectiveGit.framework/Versions/A/ObjectiveGit normal x86_64 (in target 'ObjectiveGit-Mac' from project 'ObjectiveGitFramework')
    cd /Users/crcarter/Software/Other/GitX/gitx/External/objective-git
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-macos10.8 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -L/Users/crcarter/Software/Other/GitX/gitx/build/Release -L. -LExternal -L/usr/local/opt/openssl/lib -L/Users/crcarter/Software/Other/GitX/gitx/External/objective-git/External/build/lib -F/Users/crcarter/Software/Other/GitX/gitx/build/Release -filelist /Users/crcarter/Library/Developer/Xcode/DerivedData/GitX-fuwqtzoxlnpfhxcovjaqievpfxyk/Build/Intermediates.noindex/ObjectiveGitFramework.build/Release/ObjectiveGit-Mac.build/Objects-normal/x86_64/ObjectiveGit.LinkFileList -install_name @rpath/ObjectiveGit.framework/ObjectiveGit -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/../Frameworks -Xlinker -object_path_lto -Xlinker /Users/crcarter/Library/Developer/Xcode/DerivedData/GitX-fuwqtzoxlnpfhxcovjaqievpfxyk/Build/Intermediates.noindex/ObjectiveGitFramework.build/Release/ObjectiveGit-Mac.build/Objects-normal/x86_64/ObjectiveGit_lto.o -fobjc-arc -fobjc-link-runtime -fapplication-extension -lgit2 -force_load External/libgit2.a /usr/local/lib/libssh2.a -lcrypto -lssl -lcurl -lz -liconv -lgit2 -framework Cocoa -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/crcarter/Library/Developer/Xcode/DerivedData/GitX-fuwqtzoxlnpfhxcovjaqievpfxyk/Build/Intermediates.noindex/ObjectiveGitFramework.build/Release/ObjectiveGit-Mac.build/Objects-normal/x86_64/ObjectiveGit_dependency_info.dat -o /Users/crcarter/Software/Other/GitX/gitx/build/Release/ObjectiveGit.framework/Versions/A/ObjectiveGit
ld: warning: directory not found for option '-L/Users/crcarter/Software/Other/GitX/gitx/External/objective-git/External/build/lib'
ld: warning: linking against a dylib which is not safe for use in application extensions: /usr/local/opt/openssl/lib/libcrypto.dylib
ld: warning: linking against a dylib which is not safe for use in application extensions: /usr/local/opt/openssl/lib/libssl.dylib
Undefined symbols for architecture x86_64:
  "_EVP_CIPHER_CTX_cleanup", referenced from:
      _aes_ctr_cleanup in libssh2.a(openssl.c.o)
      _crypt_dtor in libssh2.a(crypt.c.o)
  "_EVP_CIPHER_CTX_init", referenced from:
      __libssh2_cipher_init in libssh2.a(openssl.c.o)
  "_EVP_MD_CTX_init", referenced from:
      _libssh2_sha1 in libssh2.a(openssl.c.o)
      _libssh2_sha1_init in libssh2.a(openssl.c.o)
      _libssh2_md5_init in libssh2.a(openssl.c.o)
      _libssh2_md5 in libssh2.a(openssl.c.o)
  "_HMAC_CTX_cleanup", referenced from:
      _mac_method_hmac_ripemd160_hash in libssh2.a(mac.c.o)
      _mac_method_hmac_md5_hash in libssh2.a(mac.c.o)
      _mac_method_hmac_sha1_hash in libssh2.a(mac.c.o)
  "_HMAC_CTX_init", referenced from:
      _mac_method_hmac_ripemd160_hash in libssh2.a(mac.c.o)
      _mac_method_hmac_md5_hash in libssh2.a(mac.c.o)
      _mac_method_hmac_sha1_hash in libssh2.a(mac.c.o)
  "_OPENSSL_add_all_algorithms_noconf", referenced from:
      _libssh2_init in libssh2.a(global.c.o)
  "_OpenSSL_add_all_ciphers", referenced from:
      __libssh2_pub_priv_keyfile in libssh2.a(openssl.c.o)
      __libssh2_pub_priv_keyfilememory in libssh2.a(openssl.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm not totally out of luck, I guess, as the build provided in #194 does seem to work, but I would like to be able to build my own again.

**Comment by claytonrcarter** [comment]
Oh, also, this looks relevant: https://github.com/libgit2/objective-git/issues/699

**Comment by bcomnes** [comment]
> @bcomnes I'd be wary of simply swapping the header imports. If I understand correctly, that is precisely the scenario that homebrew is attempting to avoid: your build is pointing to homebrew's _headers_ but linking against the _non homebrew_ version.
> 
> > Warning: Refusing to link: openssl
> > Linking keg-only OpenSSL means you may end up linking against the insecure,
> > deprecated system version while using the headers from the Homebrew version.
> > Instead, pass the full include/library paths to your compiler e.g.:
> > -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib



> @bcomnes I'd be wary of simply swapping the header imports. If I understand correctly, that is precisely the scenario that homebrew is attempting to avoid: your build is pointing to homebrew's _headers_ but linking against the _non homebrew_ version.
> 
> > Warning: Refusing to link: openssl
> > Linking keg-only OpenSSL means you may end up linking against the insecure,
> > deprecated system version while using the headers from the Homebrew version.
> > Instead, pass the full include/library paths to your compiler e.g.:
> > -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib

All I know is it went from no build, to a working build that served me well.  Since switched to fork which appears to be a commercial spiritual successor to gitx, an arrangement I've been looking for a while.

**Comment by hannesa2** [comment]
I guess it's obsolete now, because we can build x86_64 and arm64.
Please reopen if it's still an issue
